#!/usr/bin/env python3
"""Generate and build the BRN design handbook.

The app's design values live in crates/brn-desktop/src/tokens.rs. This script
reads them and writes the handbook's generated token page and the CSS custom
properties used by HTML prototypes, so both show the values production uses.

Usage:
  python3 scripts/design-handbook.py tokens   # regenerate generated files
  python3 scripts/design-handbook.py check    # fail if generated files are stale
  python3 scripts/design-handbook.py build    # tokens + mdbook build
  python3 scripts/design-handbook.py open     # build, then open in the browser

mdBook 0.5.4 is used from PATH, or from target/design-tools/bin after:
  cargo install mdbook --version 0.5.4 --locked --root target/design-tools
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import webbrowser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS_RS = ROOT / "crates/brn-desktop/src/tokens.rs"
BOOK = ROOT / "docs/design"
GENERATED = BOOK / "src/generated"
TOKENS_MD = GENERATED / "tokens.md"
TOKENS_CSS = GENERATED / "tokens.css"
LOCAL_MDBOOK = ROOT / "target/design-tools/bin/mdbook"
PROTOTYPES = BOOK / "src/prototypes"
BEGIN = "/* BEGIN GENERATED TOKENS (scripts/design-handbook.py) */"
END = "/* END GENERATED TOKENS */"

ROLES = {
    "background": "Outer window and divider background",
    "panel": "Rails, composer, status strip and secondary surfaces",
    "paper": "Document, chat and reading surfaces",
    "text": "Primary text",
    "muted": "Secondary text, metadata and section labels",
    "line": "Borders and separators",
    "active": "Selected or hovered surface; question blocks",
    "cyan": "Info: focus, links, evidence (Source) and the primary action",
    "amber": "Attention: needs review, changed, waiting, follow-up",
    "purple": "AI: AI-generated or provisional content",
    "green": "Success: approved current knowledge, saved, completed",
    "red": "Danger: failure, destructive change, overdue",
}


def parse(text: str) -> dict:
    """Read palettes, fonts and numeric scales from tokens.rs literals."""
    palettes = {}
    for name in ("DARK", "LIGHT"):
        block = re.search(rf"pub const {name}: Palette = Palette \{{(.*?)\n\}};", text, re.S)
        if not block:
            raise SystemExit(f"tokens.rs: palette {name} not found")
        palettes[name.lower()] = {
            key: f"#{value.lower()}"
            for key, value in re.findall(r"^\s+(\w+): 0x([0-9a-fA-F]{6}),", block[1], re.M)
        }
    fields = re.search(r"pub struct Palette \{(.*?)\n\}", text, re.S)
    order = re.findall(r"pub (\w+): u32", fields[1]) if fields else []
    for name, values in palettes.items():
        if list(values) != order:
            raise SystemExit(f"tokens.rs: {name} palette fields {list(values)} != {order}")
    fonts = dict(re.findall(r'pub const (UI_FONT|MONO_FONT): &str = "([^"]+)";', text))
    scales = {}
    for module in ("text", "space", "size"):
        block = re.search(rf"pub mod {module} \{{(.*?)\n\}}", text, re.S)
        if not block:
            raise SystemExit(f"tokens.rs: module {module} not found")
        entries = []
        doc = []
        for line in block[1].splitlines():
            line = line.strip()
            if line.startswith("///"):
                doc.append(line[3:].strip())
            elif m := re.match(r"pub const (\w+): (?:f32|u32) = ([0-9.]+);", line):
                entries.append((m[1], m[2], " ".join(doc)))
                doc = []
        scales[module] = entries
    if set(fonts) != {"UI_FONT", "MONO_FONT"} or not order:
        raise SystemExit("tokens.rs: fonts or palette fields not found")
    return {"order": order, "palettes": palettes, "fonts": fonts, "scales": scales}


def luminance(hex_colour: str) -> float:
    channels = [int(hex_colour[i : i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


def contrast(a: str, b: str) -> float:
    la, lb = sorted((luminance(a), luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def css_font(name: str) -> str:
    if name == ".SystemUIFont":
        return '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Helvetica Neue", sans-serif'
    return f'"{name}", ui-monospace, SFMono-Regular, Menlo, monospace'


def render_css(tokens: dict) -> str:
    lines = [
        "/* GENERATED by scripts/design-handbook.py from crates/brn-desktop/src/tokens.rs. */",
        "/* Do not edit. Prototypes use these values so they match the production app. */",
        ":root {",
        f"  --brn-font-ui: {css_font(tokens['fonts']['UI_FONT'])};",
        f"  --brn-font-mono: {css_font(tokens['fonts']['MONO_FONT'])};",
    ]
    for module, entries in tokens["scales"].items():
        for name, value, _ in entries:
            lines.append(f"  --brn-{module}-{name.lower().replace('_', '-')}: {value}px;")
    lines.append("}")
    for scheme in ("dark", "light"):
        selector = ':root, [data-scheme="dark"]' if scheme == "dark" else '[data-scheme="light"]'
        lines.append(f"{selector} {{")
        for key in tokens["order"]:
            lines.append(f"  --brn-{key}: {tokens['palettes'][scheme][key]};")
        lines.append("}")
    return "\n".join(lines) + "\n"


def render_md(tokens: dict) -> str:
    out = [
        "<!-- GENERATED by scripts/design-handbook.py from crates/brn-desktop/src/tokens.rs. Do not edit. -->",
        "",
        "### Colour roles",
        "",
        "| Token | Role | Dark | Light | Contrast on paper (dark / light) |",
        "| --- | --- | --- | --- | --- |",
    ]
    dark, light = tokens["palettes"]["dark"], tokens["palettes"]["light"]
    for key in tokens["order"]:
        swatch = lambda c: f'<span style="display:inline-block;width:0.9em;height:0.9em;background:{c};border:1px solid #888;vertical-align:middle"></span> `{c}`'
        ratio = f"{contrast(dark[key], dark['paper']):.1f} / {contrast(light[key], light['paper']):.1f}"
        out.append(f"| `{key}` | {ROLES.get(key, '')} | {swatch(dark[key])} | {swatch(light[key])} | {ratio} |")
    out += [
        "",
        "Contrast is the WCAG ratio of the token against `paper`. Text tokens should stay at or above 4.5; "
        "surface tokens (`background`, `panel`, `paper`, `active`, `line`) are not text colours.",
        "",
        "### Fonts",
        "",
        "| Token | Value | Use |",
        "| --- | --- | --- |",
        f"| `UI_FONT` | `{tokens['fonts']['UI_FONT']}` (SF Pro on macOS) | Chrome, labels, chat and reading prose |",
        f"| `MONO_FONT` | `{tokens['fonts']['MONO_FONT']}` | Paths, UUIDs, model ids, byte ranges, counts, Markdown editors |",
    ]
    for module, title in (("text", "Type scale"), ("space", "Spacing"), ("size", "Sizes")):
        out += ["", f"### {title}", "", "| Token | Value | Use |", "| --- | --- | --- |"]
        for name, value, doc in tokens["scales"][module]:
            unit = "" if name == "RADIUS" else " pt"
            out.append(f"| `{module}::{name}` | {value}{unit} | {doc} |")
    return "\n".join(out) + "\n"


def embed(html: str, css: str) -> str:
    """Inline the token CSS so prototypes work from file:// in every browser
    (Safari blocks stylesheets outside the opened file's folder)."""
    start, end = html.find(BEGIN), html.find(END)
    if start < 0 or end < start:
        raise SystemExit("prototype is missing the generated-token markers")
    return html[: start + len(BEGIN)] + "\n" + css + html[end:]


def generated() -> dict[Path, str]:
    tokens = parse(TOKENS_RS.read_text(encoding="utf-8"))
    css = render_css(tokens)
    files = {TOKENS_CSS: css, TOKENS_MD: render_md(tokens)}
    for page in sorted(PROTOTYPES.glob("*.html")):
        files[page] = embed(page.read_text(encoding="utf-8"), css)
    return files


def write_tokens() -> None:
    GENERATED.mkdir(parents=True, exist_ok=True)
    for path, content in generated().items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


def check_tokens() -> int:
    stale = [p for p, c in generated().items() if not p.exists() or p.read_text(encoding="utf-8") != c]
    for path in stale:
        print(f"stale: {path.relative_to(ROOT)}; run python3 scripts/design-handbook.py tokens")
    return 1 if stale else 0


def mdbook() -> str:
    found = shutil.which("mdbook") or (str(LOCAL_MDBOOK) if LOCAL_MDBOOK.exists() else None)
    if not found:
        raise SystemExit(
            "mdBook not found. Install it locally without changing your global tools:\n"
            "  cargo install mdbook --version 0.5.4 --locked --root target/design-tools"
        )
    return found


OUTPUT = ROOT / "target/design-handbook"
HREF = re.compile(r'href="((?:\.\./)+[^"#]+)(#[^"]*)?"')


def repoint_external_links() -> int:
    """Point links that leave the book at the repository files they name.

    Book sources link to code and product docs with repository-relative paths so
    the Markdown stays valid for agents; mdBook copies those hrefs unchanged (and
    renames .md to .html), which would escape the output directory.
    """
    changed = 0
    src = BOOK / "src"
    for page in OUTPUT.rglob("*.html"):
        base = src / page.parent.relative_to(OUTPUT)

        def fix(match: re.Match) -> str:
            nonlocal changed
            target = (base / match[1]).resolve()
            if target.is_relative_to(src.resolve()):
                return match[0]
            if not target.exists() and target.suffix == ".html":
                target = target.with_suffix(".md")
            if not target.exists():
                return match[0]
            changed += 1
            return f'href="{target.as_uri()}{match[2] or ""}"'

        text = page.read_text(encoding="utf-8")
        page.write_text(HREF.sub(fix, text), encoding="utf-8")
    return changed


def build() -> Path:
    write_tokens()
    subprocess.run([mdbook(), "build", str(BOOK)], check=True)
    print(f"linked {repoint_external_links()} references to repository files")
    index = OUTPUT / "index.html"
    print(f"built {index}")
    return index


def main(argv: list[str]) -> int:
    command = argv[1] if len(argv) > 1 else "build"
    if command == "tokens":
        write_tokens()
    elif command == "check":
        return check_tokens()
    elif command == "build":
        build()
    elif command == "open":
        webbrowser.open(build().as_uri())
    else:
        print(__doc__)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
